### ISSUE TITLE
ore dicting

### ISSUE THREAD

**Issue by D4r33lMistaTwista** [BrassGoggledCoders/SteamCraft2#184]
The copper and tin ores added by your mod don't seem to be detected by mods like thaumcraft and factorization.

**Comment by warlordjones** [comment]
>.> I'm 90% certain I'm oredicting them correctly, will double check when I get a chance. What version are you using?

**Comment by D4r33lMistaTwista** [comment]
I'm using the latest version

**Comment by warlordjones** [comment]
I'm not sure that FZ Machines/The Thaumatorium use oredictionary for ores - the Tinker's Smeltery certainly didn't, I had to manually add compat for ore/metal/ingots/nuggets!

**Comment by mallrat208** [comment]
Quite a few mods use the ore dictionary in what's really a odd way. When they load they take a snapshot of all the blocks in a given tag and then create recipes for each block/item. The problem is if your mod loads after it/registers a block to the ore dictionary after it's already been checked it doesn't get caught.

**Comment by warlordjones** [comment]
Ah, that may be the way TC does it. I'll investigate.
