### ISSUE TITLE
Add a Solar Boiler

### ISSUE THREAD

**Issue by decebaldecebal** [BrassGoggledCoders/SteamCraft2#294]
I was thinking of adding some sort of Solar Boiler that heats water into steam that uses other blocks that are adjencted to it to generate the heat and you can have up to 4 blocks on the sides of the boiler which need to see the sky and for each such block the steam output increases.

I was thinking of actually buffing the current Steam Boiler and Nuclear boiler a little and have this solar boiler generate less steam than the Steam Boilers.

**Comment by warlordjones** [comment]
So basically like Factorisations Solar Boiler? Seems like it could be cool - I've doubts about how steampunky it would be though - I'm already thinking about how to change the nuclear stuff to be more steampunky.

**Comment by MyDeloreanWontStart** [comment]
Mine craft modding=copying FZ

**Comment by warlordjones** [comment]
?

**Comment by MyDeloreanWontStart** [comment]
Never mind its a circlejerk about how FZ has a lot of features that get redone

**Comment by WolfieWaffle** [comment]
Oh yes, don't get me started about FZ. I personally love it, because it provides non-OP and unique systems... that get made easier and IMO worse by other mods. Barrels? JABBA. 3x ores? Pretty much every mod nowadays. I just really liked the style of FZ and it's balance, and how solar boilers weren't just a blue-top block like every other mod.

But more to the point, I think solar boilers might be cool, but to me steampunk was never really about renewable energy. I think it could be cool for small devices, like maybe chargers, but I don't think it should be allowed to dominate other power systems. Nuclear and coal should be the ones for large power generation. For nuclear, maybe multi block structures that could explode? Not just like a 3x3 cube, but maybe multiple parts to each reactor, that are connected with pipes? It would have to be steampunk-y, of course. Maybe a bunch of strong-looking tanks surrounded by heating coils. This is making me think of mod compatibility stuff now... heating coils and stuff. Doesn't FZ have those?

**Comment by warlordjones** [comment]
That kind of multipart multiblock is what I'm planning for Beta 5 - the major stumbling block is that its something I have never done before, and don't really know how to do properly...

**Comment by WolfieWaffle** [comment]
Hmm. That sounds cool, and as for multiblock I feel the the Railcraft rock
crusher seems like a pretty simple one. IDK if it's open source, though.

**Comment by warlordjones** [comment]
Railcraft is visible source yeah. Pnematiccraft is proper opensource tho. (Plus I like MineMaarten more than Covert :P)

**Comment by decebaldecebal** [comment]
I have made multiblocks in the past for my own mod, a 2x2x2 one and also a giant one that can't be easily described in words :P
So I know how to do those, it's not really that hard once you get the hang of it.
Maybe if you could tell me what ideas you have, I could start implementing them since I find myself at a point when I do not know exactly on what to work on next :)

**Comment by warlordjones** [comment]
You don't know what to work on? Awesome, I've got plenty of stuff. There's a block called the refinery, currently commented out, which is for refining whale blubber into whale oil (both of which may also be commented out) - it doesn't work right atm, you could fix that up :)

**Comment by MyDeloreanWontStart** [comment]
Whaling? Count me in

On Jul 15, 2015 4:28 AM, "Arona Jones" <notifications@github.com> wrote:
>
> You don't know what to work on? Awesome, I've got plenty of stuff.
There's a block called the refinery, currently commented out, which is for
refining whale blubber into whale oil (both of which may also be commented
out) - it doesn't work right atm, you could fix that up :)

**Comment by warlordjones** [comment]
Yep, whaling indeed.

**Comment by MyDeloreanWontStart** [comment]
Ah crap the formatting betrays me once again

**Comment by warlordjones** [comment]
Fixed it.

**Comment by warlordjones** [comment]
Moving to the machine masterlist (#305), so closing this.
