### ISSUE TITLE
[enhancement] Copper pipe "polishing"

### ISSUE THREAD

**Issue by WolfieWaffle** [BrassGoggledCoders/SteamCraft2#313]
Right now, the copper pipes work fine, but there are a few things that could be a bit better. One thing is that sometimes the hitbox flashes randomly, I don;t know what causes it. Another thing is that when you right click with a spanner, I think it should work a bit more like the TE ducts. Namely, you should be allowed to change each connection of the pipe separately, so you could have a pipe extracting from two tanks at once, one on each side, or have a pipe pass by a tank without connecting to it.

This is low priority, but it's just one of those small things that I think when added up can increase the quality of the mod.

**Comment by decebaldecebal** [comment]
The hitbox flashing is because of the way MC handles bounding bloxes, I am not sure I can do anything about it.
The other issues was mentioned a while ago in another issue and should be possible to implement, but not right now cause I don't have the time to do it and the system needs to be changed a little for that to be implemented.
For now, just place the machine you want to extract from before the others...

**Comment by decebaldecebal** [comment]
You can now extract from all the sides of a pipe/wire independently.There is now a GUI if you sneak right-click with the spanner on pipes/wires where you can select the mode for each side.
Added in #324
