### ISSUE TITLE
bug about geoactivity

### ISSUE THREAD

**Issue by Tronio** [BrassGoggledCoders/Steamcraft2#345]
It was very difficult to found a contact to talk you about something really particular. I didnt found any URL or E-mail to say this, so Im going to tell you here.

Im from South America, countries where speak spanish, so I play Minecraft in SPANISH (SPAIN).
I was testing the mod GeoActivity 1.6 for minecraft 1.7.10 and I've found a litlle problem.

When I use the awesome and difficult "ADVANCE ORE REFINER", I try to put the gold ore in the machine, but it just dont allow me to leave the stack in the places that supposes to be there.

So, the mod have a trouble with the advance ore refiner interface and the reason is the language in the mod. I knew this because I thought to change the language to English (US) and then the machine allows me to put the gold ore in the interface and it works (giving me a lot of gold)

I hope there's could be a solution or an update fixing this. I know it´s a small trouble, but people who dont understand very well the mods functionality and dont know english will be very pleased.

Sorry again, but this was the only source to tell you this.

**Comment by decebaldecebal** [comment]
This does not really belong here...But again, I do not have an official issue tracker for my mod.

I thought I fixed this bug but it seems it slipped away somehow...Anyways, I do not know when I will fix it since I haven't been modding for quite a while and don't have a lot of time for it anymore...

In the future you can post bug reports in the comments of the project on CurseForge:
http://minecraft.curseforge.com/projects/geoactivity
